### ISSUE TITLE
Is this project dead? Any current deployment?

### ISSUE THREAD

**Issue by dumblob** [jalbam/CrossBrowdy#2]
Looks like an interesting project, but seems dead. Any news? Any current deployments? Any TODO list? Any missing features? Any issues? Compatibility with modern browsers?

**Comment by jalbam** [comment]
Hello,

Thanks for your message.

The project is alive.

Of course it is compatible with any modern browser as well as with legacy ones.

 You can find all the information here (check the "About & FAQ" section): https://crossbrowdy.com/

Cheers,
 Joan

**Comment by dumblob** [comment]
>The project is alive.

Ok.

>check the "About & FAQ" section

I did, but couldn't find answer to the questions above.

>Any news?

The news section is empty for months.

>Any current deployments?

No info whatsoever. Just few heavily commented examples (telling no story about real deployments and real issues & maintenance of such deployments).

>Any TODO list?

No info whatsoever (don't take me wrong, but the "Future" list on the main page doesn't convey any information except it looks more like some parody on older Lisp GUIs :wink:).

>Any missing features?

No info whatsoever.

>Any issues?
No info whatsoever.

>Compatibility with modern browsers?

Ah, great, thanks.

-----

So, all in all the web page doesn't say much :cry:.

**Comment by jalbam** [comment]
Hello again,

About any news, there are not many so far. It is just a framework that you can start using right now if you want to. I hope soon there will be more news but not yet as I am very busy with my job, sorry.

About the deployment, do you mean to download it? You can download it in the "Download" section of the web site (https://crossbrowdy.com/download) or here on GitHub. If you meant whether anyone used it so far, I have not had this information but possibly yes. I want to use it myself in the future for developing some games when I have free time. You can also try it if you are interested.

You can find a TODO list here: https://github.com/jalbam/CrossBrowdy/blob/master/TODO.txt

And here you have a list of known issues: https://github.com/jalbam/CrossBrowdy/blob/master/ISSUES.txt

Regarding missing features, all features that are listed in the main page are already available and not missing. They are documented in the API (https://crossbrowdy.com/api) as well as in the "Guides & Tutorials" section (https://crossbrowdy.com/guides).

Hope this can help somehow.

Cheers,
 Joan

**Comment by dumblob** [comment]
Now I see, thanks.

>About the deployment, do you mean to download it?

No. I meant *use of CrossBrowdy in production & running apps".

>Regarding missing features, all features that are listed in the main page are already available and not missing. They are documented in the API (https://crossbrowdy.com/api) as well as in the "Guides & Tutorials" section (https://crossbrowdy.com/guides).

Might be worth centralizing this scattered information...

Overall my questions are answered, so I'm closing this for the lack of actionable items. Cheers.

**Comment by anonimo82** [comment]
@jalbam Same question, is this project still alive?
I see you didn't reply to my issues, so wondering.

**Comment by jalbam** [comment]
Sorry for not replying on time.

CrossBrowdy framework is still alive but I lack of time right now because of my job and personal life in these moments.

As I said, you can find some example projects on the Guides section as for example a CHIP-8 emulator and others. I encourage you to try to develop your own project with CrossBrowdy framework if you are interested, as for example some game or multimedia app.

Thanks!
