### ISSUE TITLE
AI and Physics

### ISSUE THREAD

**Issue by anonimo82** [jalbam/CrossBrowdy#4]
Please, can you integrate:
Yuka (https://mugen87.github.io/yuka/),
MatterJS (https://brm.io/matter-js/) and
AmmoJS (https://github.com/kripken/ammo.js/)
in your framework? 

Thanks in advance for anything.

**Comment by anonimo82** [comment]
@jalbam any feedback?

**Comment by anonimo82** [comment]
Also worth noting that MatterJS also support SVG, so providing polyfills for SVG could improve CrossBrowdy regardless integrating MatterJS or not

**Comment by jalbam** [comment]
Hello,

Thanks for your messages.

You can load any of these things inside your project and use them together with CrossBrowdy. If you want more integrarion, you can also create a CrossBrowdy module to load the item or items you want (I would recommdend reading the documentation on the official site to accomplish that).

Sorry for the late reply.

Best regards,
 Joan

**Comment by anonimo82** [comment]
Yep, I know I can write a plugin or make those libraries work together in parallel, but both options would enforce me to deep dive in the library for the best integration strategy, which could double the required time and effort (in thw best situation).
So, I'm kindly asking, can you integrate these for your users? (me included).
By the way, I have a question: can I use CB for 3D graphics?

**Comment by jalbam** [comment]
I am sorry, now I do not have time for this and there are more prioritary things for CrossBrowdy project right now but you can consider developing that and perform a pull request. Or you can just load both CrossBrowdy framework and a physics library and use them together to make your project without having to build code to integrate CrossBrowdy with the library at all. They should not be incompatible to be used together.
And yes, you can use 3D graphics, of course.
Thanks!

**Comment by anonimo82** [comment]
I'm displeased to know this, also because in CB website it's written you plan adding these features, but the deliver time is unknown.
But, this is your project, so, pleased or not, I just can wait and see if and when you'll have time and will in doing so.
I'm not a very JavaScript guy, I'm more of an HTML one, otherwise I'd have been helped as I could.
My favorite CB feature is that it provides polyfills, which are the most important feature in any web App nowadays.

**Comment by jalbam** [comment]
It is true, physics support are in the pipeline and planned for the future although not yet because of my lack of time, sadly. So currenty, the best option would be to just use CrossBrowdy in combination with a physics library, loading and using them together in any desired project.

**Comment by anonimo82** [comment]
So sad =(
I'll just wait.
Also, don't forget Yuka for AI

**Comment by jalbam** [comment]
Sure, thanks!
