### ISSUE TITLE
Are jQuery and/or BootStrap integrated in this framework?

### ISSUE THREAD

**Issue by anonimo82** [jalbam/CrossBrowdy#5]
Hello everyone.
As in subject, are jQuery and/or BootStrap integrated with CrossBrowdy?
It would be cool, or at least, something similar.

Thanks in advance for any help.
@jalbam

**Comment by jalbam** [comment]
Hello,

They are not integrated as jQuery is not needed by me normally for most projects using CrossBrowdy and Bootstrap can be used if desired later (I do not use it either). You can just load jQuery library in your project and use it freely together with CrossBrowdy. The same with Bootstrap, of course.

Sorry for the late response.

Cheers,
 Joan

**Comment by anonimo82** [comment]
No, thanks, I don't really need either one.
I thought jQuery would have been a good addition because of its legacy browser support in v1.x, but as CB is more media - and less textual - content oriented, I guess this is really out of scope

**Comment by jalbam** [comment]
I agree with you. Just note that some functions that jQuery provide, or similar ones, are implemented in CrossBrowdy as can be seen in CB_Elements class and other parts.

**Comment by anonimo82** [comment]
Wow, this is really good news! =)
