### ISSUE TITLE
Do you mind x3D?

### ISSUE THREAD

**Issue by anonimo82** [jalbam/CrossBrowdy#6]
Hello @jalbam, I promise to not bother you any further after this request.
I'd like to suggest you to also support x3D by integrating X_Ite (https://github.com/create3000/x_ite) in CrossBrowdy.

I hope you'll consider my ideas.

I take advantage to wish you a nice holidays, merry Christmas and a GREAT new year, also extend to your relatives.
May God bless you all =)

**Comment by jalbam** [comment]
Hello,

Thanks for your message.

CrossBrowdy is ready to support that library or any other. If you need more integration, you can create a CrossBrowdy module with it and even perform a pull request with your desired changes.

Sorry for the late reply.

Best regards,
 Joan

**Comment by anonimo82** [comment]
Uhm, I guess this is not really important, unless 3D is out of scope for this project.
By the way, same considerations apply as in my other issue's last message (https://github.com/jalbam/CrossBrowdy/issues/4#issuecomment-1071352502)
Just wondering if is WebGL available in CB, which would invalidate my request if so

**Comment by jalbam** [comment]
Yes, WebGL can be used in CB_Canvas class

**Comment by anonimo82** [comment]
What a relief =) thanks

**Comment by jalbam** [comment]
You are welcome, thanks to you for your messages and interest
