### ISSUE TITLE
Examples not working - IntelliSense fails

### ISSUE THREAD

**Issue by anonimo82** [jalbam/CrossBrowdy#7]
Hello @jalbam,
I downloaded the examples, and I can't run any.
I also tried to write a simple page, shown below:
```
<!DOCTYPE html>
<html>
    <head>
        <title>
            CrossBrowdy - Intellisense Test
        </title>
        <script src="CrossBrowdy/CrossBrowdy.js" type="text/javascript" language="javascript"></script>
        <script type="text/javascript" language="javascript">
         alert("done");
        </script>
    </head>
    <body>

    </body>
</html>

```
But, IntelliSense won't trigger, despite I guess I recognized type annotations in the script.

I guess I need NodeJs, do I?

**Comment by jalbam** [comment]
Hello,

The examples are ready to be opened with any web browser. You can just double click them, but better if you access to them through a local web server to get rid of some restrictions that might be encountered.

I guess that IntelliSense error is not related with CrossBrowdy framework at all.

You should assure that paths are correct too.

Here you have a very basic example: https://crossbrowdy.com/basic_tutorial/general/getting_started

Best regards,
 Joan

**Comment by anonimo82** [comment]
No, indeed, IntelliSense is not related to CB specifically, but in example, it was working when I tried with jQuery.
Ok, so now I'm gonna try with my test server, I'll update you ASAP

**Comment by anonimo82** [comment]
Yep, examples now work
