### ISSUE TITLE
support DualSense ? 

### ISSUE THREAD

**Issue by 3biubiu** [jalbam/CrossBrowdy#8]
like adaptive trigger

**Comment by jalbam** [comment]
Hello,

I do not have one for testing, but most basic features should work out of the box already. You can read this post on Reddit: https://www.reddit.com/r/learnjavascript/comments/kn0dhd/gamepad_api_with_ps5_dualsense_controller/

For other advanced and specific features of the DualSense gamepads you could perhaps use WebHID API or a library, maybe this one (never tried myself): https://github.com/equalent/DualSense.js/blob/main/src/index.ts

If you own one you could try it.

Cheers,
 Joan

**Comment by 3biubiu** [comment]
> Hello,
> 
> I do not have one for testing, but most basic features should work out of the box already. You can read this post on Reddit: https://www.reddit.com/r/learnjavascript/comments/kn0dhd/gamepad_api_with_ps5_dualsense_controller/
> 
> For other advanced and specific features of the DualSense gamepads you could perhaps use WebHID API or a library, maybe this one (never tried myself): https://github.com/equalent/DualSense.js/blob/main/src/index.ts
> 
> If you own one you could try it.
> 
> Cheers, Joan

thank you

**Comment by jalbam** [comment]
You are welcome. Feel free to contact again for anything. Thanks!
